name: Build Stencil Jest Runner

on:
  workflow_call:
  # Make this a reusable workflow, no value needed
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows

jobs:
  build_stencil_jest_runner:
    name: Build Stencil Jest Runner
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # the pull_request_target event will consider the HEAD of `main` to be the SHA to use.
          # attempt to use the SHA associated with a pull request and fallback to HEAD of `main`
          ref: ${{ github.event_name == 'pull_request_target' && format('refs/pull/{0}/merge', github.event.number) || '' }}
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Stencil Jest Runner
        run: pnpm run build
        shell: bash

      - name: Upload Build Artifacts
        uses: stenciljs/.github/actions/upload-archive@main